import type { Article, AIInsights } from '@/types';

export const mockArticles: Article[] = [
  {
    pmid: "38123456",
    title: "Effects of High-Intensity Interval Training on Glycemic Control in Adults with Type 2 Diabetes: A Randomized Controlled Trial",
    authors: [
      { name: "Smith J", affiliation: "Harvard Medical School" },
      { name: "Johnson M", affiliation: "Mayo Clinic" },
      { name: "Williams K", affiliation: "Stanford University" },
    ],
    journal: "Journal of Clinical Endocrinology",
    journalAbbrev: "J Clin Endocrinol",
    pubDate: "2024-01-15",
    abstract: "Background: High-intensity interval training (HIIT) has emerged as a time-efficient exercise modality. Objective: To evaluate the effects of HIIT compared to moderate-intensity continuous training (MICT) on glycemic control in adults with type 2 diabetes. Methods: We conducted a 12-week randomized controlled trial with 120 participants. Results: HIIT significantly improved HbA1c levels (-0.8% vs -0.4%, p<0.001) compared to MICT. Secondary outcomes including fasting glucose and insulin sensitivity also showed significant improvements. Conclusion: HIIT represents an effective and time-efficient exercise strategy for improving glycemic control in type 2 diabetes.",
    aiSummary: "This 12-week RCT found that high-intensity interval training improved HbA1c levels more effectively than traditional moderate exercise in type 2 diabetes patients, with -0.8% reduction vs -0.4%.",
    doi: "10.1210/jc.2024-00123",
    pmcId: "PMC10234567",
    hasFullText: true,
    meshTerms: ["Diabetes Mellitus, Type 2", "High-Intensity Interval Training", "Glycemic Control", "Exercise Therapy"],
    keywords: ["HIIT", "diabetes", "exercise intervention", "metabolic health"],
    pubTypes: ["Randomized Controlled Trial", "Journal Article"],
    relevanceScore: 94,
    url: "https://pubmed.ncbi.nlm.nih.gov/38123456/",
  },
  {
    pmid: "38123457",
    title: "Metformin and Cardiovascular Outcomes in Patients with Type 2 Diabetes: A Systematic Review and Meta-Analysis",
    authors: [
      { name: "Chen L", affiliation: "Johns Hopkins University" },
      { name: "Garcia R", affiliation: "UCLA Medical Center" },
    ],
    journal: "Diabetes Care",
    journalAbbrev: "Diabetes Care",
    pubDate: "2024-02-01",
    abstract: "Objective: To systematically review the cardiovascular effects of metformin in patients with type 2 diabetes. Methods: We searched PubMed, Embase, and Cochrane Library for randomized controlled trials comparing metformin with placebo or other antidiabetic agents. Results: 45 studies with 67,000 participants were included. Metformin was associated with a 20% reduction in major adverse cardiovascular events (HR 0.80, 95% CI 0.72-0.89). Conclusions: Metformin provides significant cardiovascular protection in patients with type 2 diabetes.",
    aiSummary: "Meta-analysis of 45 RCTs (67,000 patients) shows metformin reduces major cardiovascular events by 20% in type 2 diabetes patients.",
    doi: "10.2337/dc24-0156",
    pmcId: "PMC10234568",
    hasFullText: true,
    meshTerms: ["Metformin", "Cardiovascular Diseases", "Diabetes Mellitus, Type 2", "Meta-Analysis"],
    keywords: ["cardiovascular outcomes", "metformin", "diabetes treatment"],
    pubTypes: ["Meta-Analysis", "Systematic Review"],
    relevanceScore: 91,
    url: "https://pubmed.ncbi.nlm.nih.gov/38123457/",
  },
  {
    pmid: "38123458",
    title: "Continuous Glucose Monitoring in Gestational Diabetes: Impact on Maternal and Neonatal Outcomes",
    authors: [
      { name: "Thompson A", affiliation: "University of Michigan" },
      { name: "Miller S", affiliation: "Cleveland Clinic" },
      { name: "Davis E", affiliation: "Duke University" },
      { name: "Wilson P", affiliation: "Mount Sinai Hospital" },
    ],
    journal: "Obstetrics & Gynecology",
    journalAbbrev: "Obstet Gynecol",
    pubDate: "2024-01-20",
    abstract: "Objective: To assess the effectiveness of continuous glucose monitoring (CGM) compared to self-monitoring of blood glucose in women with gestational diabetes mellitus. Methods: Prospective cohort study of 280 pregnant women. Results: CGM use was associated with better glycemic control and reduced rates of large-for-gestational-age infants (18% vs 28%, p=0.04). Neonatal hypoglycemia was also less frequent in the CGM group.",
    aiSummary: "Continuous glucose monitoring in gestational diabetes leads to better glycemic control and fewer large-for-gestational-age infants compared to traditional blood glucose self-monitoring.",
    doi: "10.1097/AOG.0000000000005321",
    hasFullText: false,
    meshTerms: ["Gestational Diabetes", "Blood Glucose Self-Monitoring", "Pregnancy Outcome"],
    keywords: ["CGM", "gestational diabetes", "pregnancy"],
    pubTypes: ["Clinical Trial", "Journal Article"],
    relevanceScore: 87,
    url: "https://pubmed.ncbi.nlm.nih.gov/38123458/",
  },
  {
    pmid: "38123459",
    title: "GLP-1 Receptor Agonists and Weight Loss: Mechanisms of Action and Clinical Applications",
    authors: [
      { name: "Brown R", affiliation: "Columbia University" },
    ],
    journal: "Nature Reviews Endocrinology",
    journalAbbrev: "Nat Rev Endocrinol",
    pubDate: "2024-02-15",
    abstract: "GLP-1 receptor agonists have revolutionized the treatment of type 2 diabetes and obesity. This review examines the molecular mechanisms underlying their metabolic effects, including appetite suppression, delayed gastric emptying, and enhanced insulin secretion. We discuss the clinical evidence for weight loss efficacy across different GLP-1 agonists and their potential cardiovascular and renal benefits. Future directions including oral formulations and combination therapies are also explored.",
    aiSummary: "Comprehensive review of GLP-1 receptor agonists covering mechanisms (appetite suppression, delayed gastric emptying), clinical weight loss evidence, and emerging therapies.",
    doi: "10.1038/s41574-024-00956-2",
    pmcId: "PMC10234570",
    hasFullText: true,
    meshTerms: ["GLP-1 Receptor Agonists", "Weight Loss", "Obesity", "Diabetes Mellitus, Type 2"],
    keywords: ["semaglutide", "tirzepatide", "obesity treatment", "incretin"],
    pubTypes: ["Review"],
    relevanceScore: 85,
    url: "https://pubmed.ncbi.nlm.nih.gov/38123459/",
  },
  {
    pmid: "38123460",
    title: "Case Report: Severe Hypoglycemia Following Insulin Overdose in a Patient with Type 1 Diabetes",
    authors: [
      { name: "Lee K", affiliation: "University of Washington" },
      { name: "Park J", affiliation: "University of Washington" },
    ],
    journal: "Journal of Emergency Medicine",
    journalAbbrev: "J Emerg Med",
    pubDate: "2024-01-25",
    abstract: "We present a case of a 34-year-old woman with type 1 diabetes who presented to the emergency department following intentional insulin overdose. Despite initial blood glucose of 18 mg/dL, the patient was successfully managed with continuous dextrose infusion and glucagon administration. This case highlights the importance of prolonged monitoring and individualized treatment approaches in insulin overdose.",
    aiSummary: "Case report describing successful management of severe hypoglycemia (glucose 18 mg/dL) from intentional insulin overdose using continuous dextrose and glucagon.",
    doi: "10.1016/j.jemermed.2024.01.012",
    hasFullText: false,
    meshTerms: ["Hypoglycemia", "Insulin Overdose", "Type 1 Diabetes", "Emergency Treatment"],
    keywords: ["insulin overdose", "hypoglycemia management", "emergency medicine"],
    pubTypes: ["Case Reports"],
    relevanceScore: 72,
    url: "https://pubmed.ncbi.nlm.nih.gov/38123460/",
  },
];

export const mockInsights: AIInsights = {
  summary: "These results focus on diabetes management, with emphasis on lifestyle interventions, glucose monitoring technologies, and pharmacological treatments. Clinical trials and meta-analyses dominate the high-relevance findings.",
  themes: ["Glycemic Control", "Exercise Therapy", "GLP-1 Agonists", "Continuous Monitoring"],
  suggestedQueries: ["SGLT2 inhibitors diabetes", "insulin pump therapy", "diabetes prevention lifestyle"],
};
